// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface AddressesMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.AddressesMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto_java.NetAddress addressList = 1;</code>
   */
  java.util.List<proto_java.NetAddress> 
      getAddressListList();
  /**
   * <code>repeated .proto_java.NetAddress addressList = 1;</code>
   */
  proto_java.NetAddress getAddressList(int index);
  /**
   * <code>repeated .proto_java.NetAddress addressList = 1;</code>
   */
  int getAddressListCount();
  /**
   * <code>repeated .proto_java.NetAddress addressList = 1;</code>
   */
  java.util.List<? extends proto_java.NetAddressOrBuilder> 
      getAddressListOrBuilderList();
  /**
   * <code>repeated .proto_java.NetAddress addressList = 1;</code>
   */
  proto_java.NetAddressOrBuilder getAddressListOrBuilder(
      int index);
}
