// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface GetBlocksRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.GetBlocksRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lowHash = 1;</code>
   * @return The lowHash.
   */
  java.lang.String getLowHash();
  /**
   * <code>string lowHash = 1;</code>
   * @return The bytes for lowHash.
   */
  com.google.protobuf.ByteString
      getLowHashBytes();

  /**
   * <code>bool includeBlocks = 2;</code>
   * @return The includeBlocks.
   */
  boolean getIncludeBlocks();

  /**
   * <code>bool includeTransactions = 3;</code>
   * @return The includeTransactions.
   */
  boolean getIncludeTransactions();
}
