// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface GetBalancesByAddressesResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.GetBalancesByAddressesResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto_java.BalancesByAddressEntry entries = 1;</code>
   */
  java.util.List<proto_java.BalancesByAddressEntry> 
      getEntriesList();
  /**
   * <code>repeated .proto_java.BalancesByAddressEntry entries = 1;</code>
   */
  proto_java.BalancesByAddressEntry getEntries(int index);
  /**
   * <code>repeated .proto_java.BalancesByAddressEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .proto_java.BalancesByAddressEntry entries = 1;</code>
   */
  java.util.List<? extends proto_java.BalancesByAddressEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .proto_java.BalancesByAddressEntry entries = 1;</code>
   */
  proto_java.BalancesByAddressEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return The error.
   */
  proto_java.RPCError getError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   */
  proto_java.RPCErrorOrBuilder getErrorOrBuilder();
}
