// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

/**
 * Protobuf type {@code proto_java.GetConnectedPeerInfoMessage}
 */
public final class GetConnectedPeerInfoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto_java.GetConnectedPeerInfoMessage)
    GetConnectedPeerInfoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetConnectedPeerInfoMessage.newBuilder() to construct.
  private GetConnectedPeerInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetConnectedPeerInfoMessage() {
    id_ = "";
    address_ = "";
    userAgent_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetConnectedPeerInfoMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetConnectedPeerInfoMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 24: {

            lastPingDuration_ = input.readInt64();
            break;
          }
          case 48: {

            isOutbound_ = input.readBool();
            break;
          }
          case 56: {

            timeOffset_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            userAgent_ = s;
            break;
          }
          case 72: {

            advertisedProtocolVersion_ = input.readUInt32();
            break;
          }
          case 80: {

            timeConnected_ = input.readInt64();
            break;
          }
          case 88: {

            isIbdPeer_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto_java.Rpc.internal_static_org_example_grpc_GetConnectedPeerInfoMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto_java.Rpc.internal_static_org_example_grpc_GetConnectedPeerInfoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto_java.GetConnectedPeerInfoMessage.class, proto_java.GetConnectedPeerInfoMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTPINGDURATION_FIELD_NUMBER = 3;
  private long lastPingDuration_;
  /**
   * <pre>
   * How long did the last ping/pong exchange take
   * </pre>
   *
   * <code>int64 lastPingDuration = 3;</code>
   * @return The lastPingDuration.
   */
  @java.lang.Override
  public long getLastPingDuration() {
    return lastPingDuration_;
  }

  public static final int ISOUTBOUND_FIELD_NUMBER = 6;
  private boolean isOutbound_;
  /**
   * <pre>
   * Whether this kaspad initiated the connection
   * </pre>
   *
   * <code>bool isOutbound = 6;</code>
   * @return The isOutbound.
   */
  @java.lang.Override
  public boolean getIsOutbound() {
    return isOutbound_;
  }

  public static final int TIMEOFFSET_FIELD_NUMBER = 7;
  private long timeOffset_;
  /**
   * <code>int64 timeOffset = 7;</code>
   * @return The timeOffset.
   */
  @java.lang.Override
  public long getTimeOffset() {
    return timeOffset_;
  }

  public static final int USERAGENT_FIELD_NUMBER = 8;
  private volatile java.lang.Object userAgent_;
  /**
   * <code>string userAgent = 8;</code>
   * @return The userAgent.
   */
  @java.lang.Override
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <code>string userAgent = 8;</code>
   * @return The bytes for userAgent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADVERTISEDPROTOCOLVERSION_FIELD_NUMBER = 9;
  private int advertisedProtocolVersion_;
  /**
   * <pre>
   * The protocol version that this peer claims to support
   * </pre>
   *
   * <code>uint32 advertisedProtocolVersion = 9;</code>
   * @return The advertisedProtocolVersion.
   */
  @java.lang.Override
  public int getAdvertisedProtocolVersion() {
    return advertisedProtocolVersion_;
  }

  public static final int TIMECONNECTED_FIELD_NUMBER = 10;
  private long timeConnected_;
  /**
   * <pre>
   * The timestamp of when this peer connected to this kaspad
   * </pre>
   *
   * <code>int64 timeConnected = 10;</code>
   * @return The timeConnected.
   */
  @java.lang.Override
  public long getTimeConnected() {
    return timeConnected_;
  }

  public static final int ISIBDPEER_FIELD_NUMBER = 11;
  private boolean isIbdPeer_;
  /**
   * <pre>
   * Whether this peer is the IBD peer (if IBD is running)
   * </pre>
   *
   * <code>bool isIbdPeer = 11;</code>
   * @return The isIbdPeer.
   */
  @java.lang.Override
  public boolean getIsIbdPeer() {
    return isIbdPeer_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
    }
    if (lastPingDuration_ != 0L) {
      output.writeInt64(3, lastPingDuration_);
    }
    if (isOutbound_ != false) {
      output.writeBool(6, isOutbound_);
    }
    if (timeOffset_ != 0L) {
      output.writeInt64(7, timeOffset_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userAgent_);
    }
    if (advertisedProtocolVersion_ != 0) {
      output.writeUInt32(9, advertisedProtocolVersion_);
    }
    if (timeConnected_ != 0L) {
      output.writeInt64(10, timeConnected_);
    }
    if (isIbdPeer_ != false) {
      output.writeBool(11, isIbdPeer_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
    }
    if (lastPingDuration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, lastPingDuration_);
    }
    if (isOutbound_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isOutbound_);
    }
    if (timeOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timeOffset_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userAgent_);
    }
    if (advertisedProtocolVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, advertisedProtocolVersion_);
    }
    if (timeConnected_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, timeConnected_);
    }
    if (isIbdPeer_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, isIbdPeer_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto_java.GetConnectedPeerInfoMessage)) {
      return super.equals(obj);
    }
    proto_java.GetConnectedPeerInfoMessage other = (proto_java.GetConnectedPeerInfoMessage) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getLastPingDuration()
        != other.getLastPingDuration()) return false;
    if (getIsOutbound()
        != other.getIsOutbound()) return false;
    if (getTimeOffset()
        != other.getTimeOffset()) return false;
    if (!getUserAgent()
        .equals(other.getUserAgent())) return false;
    if (getAdvertisedProtocolVersion()
        != other.getAdvertisedProtocolVersion()) return false;
    if (getTimeConnected()
        != other.getTimeConnected()) return false;
    if (getIsIbdPeer()
        != other.getIsIbdPeer()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + LASTPINGDURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastPingDuration());
    hash = (37 * hash) + ISOUTBOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOutbound());
    hash = (37 * hash) + TIMEOFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeOffset());
    hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + ADVERTISEDPROTOCOLVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAdvertisedProtocolVersion();
    hash = (37 * hash) + TIMECONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeConnected());
    hash = (37 * hash) + ISIBDPEER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsIbdPeer());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_java.GetConnectedPeerInfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto_java.GetConnectedPeerInfoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto_java.GetConnectedPeerInfoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto_java.GetConnectedPeerInfoMessage)
      proto_java.GetConnectedPeerInfoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_java.Rpc.internal_static_org_example_grpc_GetConnectedPeerInfoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_java.Rpc.internal_static_org_example_grpc_GetConnectedPeerInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_java.GetConnectedPeerInfoMessage.class, proto_java.GetConnectedPeerInfoMessage.Builder.class);
    }

    // Construct using proto_java.GetConnectedPeerInfoMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      address_ = "";

      lastPingDuration_ = 0L;

      isOutbound_ = false;

      timeOffset_ = 0L;

      userAgent_ = "";

      advertisedProtocolVersion_ = 0;

      timeConnected_ = 0L;

      isIbdPeer_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto_java.Rpc.internal_static_org_example_grpc_GetConnectedPeerInfoMessage_descriptor;
    }

    @java.lang.Override
    public proto_java.GetConnectedPeerInfoMessage getDefaultInstanceForType() {
      return proto_java.GetConnectedPeerInfoMessage.getDefaultInstance();
    }

    @java.lang.Override
    public proto_java.GetConnectedPeerInfoMessage build() {
      proto_java.GetConnectedPeerInfoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto_java.GetConnectedPeerInfoMessage buildPartial() {
      proto_java.GetConnectedPeerInfoMessage result = new proto_java.GetConnectedPeerInfoMessage(this);
      result.id_ = id_;
      result.address_ = address_;
      result.lastPingDuration_ = lastPingDuration_;
      result.isOutbound_ = isOutbound_;
      result.timeOffset_ = timeOffset_;
      result.userAgent_ = userAgent_;
      result.advertisedProtocolVersion_ = advertisedProtocolVersion_;
      result.timeConnected_ = timeConnected_;
      result.isIbdPeer_ = isIbdPeer_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto_java.GetConnectedPeerInfoMessage) {
        return mergeFrom((proto_java.GetConnectedPeerInfoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto_java.GetConnectedPeerInfoMessage other) {
      if (other == proto_java.GetConnectedPeerInfoMessage.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getLastPingDuration() != 0L) {
        setLastPingDuration(other.getLastPingDuration());
      }
      if (other.getIsOutbound() != false) {
        setIsOutbound(other.getIsOutbound());
      }
      if (other.getTimeOffset() != 0L) {
        setTimeOffset(other.getTimeOffset());
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (other.getAdvertisedProtocolVersion() != 0) {
        setAdvertisedProtocolVersion(other.getAdvertisedProtocolVersion());
      }
      if (other.getTimeConnected() != 0L) {
        setTimeConnected(other.getTimeConnected());
      }
      if (other.getIsIbdPeer() != false) {
        setIsIbdPeer(other.getIsIbdPeer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto_java.GetConnectedPeerInfoMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto_java.GetConnectedPeerInfoMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private long lastPingDuration_ ;
    /**
     * <pre>
     * How long did the last ping/pong exchange take
     * </pre>
     *
     * <code>int64 lastPingDuration = 3;</code>
     * @return The lastPingDuration.
     */
    @java.lang.Override
    public long getLastPingDuration() {
      return lastPingDuration_;
    }
    /**
     * <pre>
     * How long did the last ping/pong exchange take
     * </pre>
     *
     * <code>int64 lastPingDuration = 3;</code>
     * @param value The lastPingDuration to set.
     * @return This builder for chaining.
     */
    public Builder setLastPingDuration(long value) {
      
      lastPingDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How long did the last ping/pong exchange take
     * </pre>
     *
     * <code>int64 lastPingDuration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastPingDuration() {
      
      lastPingDuration_ = 0L;
      onChanged();
      return this;
    }

    private boolean isOutbound_ ;
    /**
     * <pre>
     * Whether this kaspad initiated the connection
     * </pre>
     *
     * <code>bool isOutbound = 6;</code>
     * @return The isOutbound.
     */
    @java.lang.Override
    public boolean getIsOutbound() {
      return isOutbound_;
    }
    /**
     * <pre>
     * Whether this kaspad initiated the connection
     * </pre>
     *
     * <code>bool isOutbound = 6;</code>
     * @param value The isOutbound to set.
     * @return This builder for chaining.
     */
    public Builder setIsOutbound(boolean value) {
      
      isOutbound_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this kaspad initiated the connection
     * </pre>
     *
     * <code>bool isOutbound = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOutbound() {
      
      isOutbound_ = false;
      onChanged();
      return this;
    }

    private long timeOffset_ ;
    /**
     * <code>int64 timeOffset = 7;</code>
     * @return The timeOffset.
     */
    @java.lang.Override
    public long getTimeOffset() {
      return timeOffset_;
    }
    /**
     * <code>int64 timeOffset = 7;</code>
     * @param value The timeOffset to set.
     * @return This builder for chaining.
     */
    public Builder setTimeOffset(long value) {
      
      timeOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeOffset = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeOffset() {
      
      timeOffset_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>string userAgent = 8;</code>
     * @return The userAgent.
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userAgent = 8;</code>
     * @return The bytes for userAgent.
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userAgent = 8;</code>
     * @param value The userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserAgent() {
      
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 8;</code>
     * @param value The bytes for userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAgent_ = value;
      onChanged();
      return this;
    }

    private int advertisedProtocolVersion_ ;
    /**
     * <pre>
     * The protocol version that this peer claims to support
     * </pre>
     *
     * <code>uint32 advertisedProtocolVersion = 9;</code>
     * @return The advertisedProtocolVersion.
     */
    @java.lang.Override
    public int getAdvertisedProtocolVersion() {
      return advertisedProtocolVersion_;
    }
    /**
     * <pre>
     * The protocol version that this peer claims to support
     * </pre>
     *
     * <code>uint32 advertisedProtocolVersion = 9;</code>
     * @param value The advertisedProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAdvertisedProtocolVersion(int value) {
      
      advertisedProtocolVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The protocol version that this peer claims to support
     * </pre>
     *
     * <code>uint32 advertisedProtocolVersion = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdvertisedProtocolVersion() {
      
      advertisedProtocolVersion_ = 0;
      onChanged();
      return this;
    }

    private long timeConnected_ ;
    /**
     * <pre>
     * The timestamp of when this peer connected to this kaspad
     * </pre>
     *
     * <code>int64 timeConnected = 10;</code>
     * @return The timeConnected.
     */
    @java.lang.Override
    public long getTimeConnected() {
      return timeConnected_;
    }
    /**
     * <pre>
     * The timestamp of when this peer connected to this kaspad
     * </pre>
     *
     * <code>int64 timeConnected = 10;</code>
     * @param value The timeConnected to set.
     * @return This builder for chaining.
     */
    public Builder setTimeConnected(long value) {
      
      timeConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The timestamp of when this peer connected to this kaspad
     * </pre>
     *
     * <code>int64 timeConnected = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeConnected() {
      
      timeConnected_ = 0L;
      onChanged();
      return this;
    }

    private boolean isIbdPeer_ ;
    /**
     * <pre>
     * Whether this peer is the IBD peer (if IBD is running)
     * </pre>
     *
     * <code>bool isIbdPeer = 11;</code>
     * @return The isIbdPeer.
     */
    @java.lang.Override
    public boolean getIsIbdPeer() {
      return isIbdPeer_;
    }
    /**
     * <pre>
     * Whether this peer is the IBD peer (if IBD is running)
     * </pre>
     *
     * <code>bool isIbdPeer = 11;</code>
     * @param value The isIbdPeer to set.
     * @return This builder for chaining.
     */
    public Builder setIsIbdPeer(boolean value) {
      
      isIbdPeer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this peer is the IBD peer (if IBD is running)
     * </pre>
     *
     * <code>bool isIbdPeer = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsIbdPeer() {
      
      isIbdPeer_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto_java.GetConnectedPeerInfoMessage)
  }

  // @@protoc_insertion_point(class_scope:proto_java.GetConnectedPeerInfoMessage)
  private static final proto_java.GetConnectedPeerInfoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto_java.GetConnectedPeerInfoMessage();
  }

  public static proto_java.GetConnectedPeerInfoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetConnectedPeerInfoMessage>
      PARSER = new com.google.protobuf.AbstractParser<GetConnectedPeerInfoMessage>() {
    @java.lang.Override
    public GetConnectedPeerInfoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetConnectedPeerInfoMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetConnectedPeerInfoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetConnectedPeerInfoMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto_java.GetConnectedPeerInfoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

