// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface GetConnectedPeerInfoResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.GetConnectedPeerInfoResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto_java.GetConnectedPeerInfoMessage infos = 1;</code>
   */
  java.util.List<proto_java.GetConnectedPeerInfoMessage> 
      getInfosList();
  /**
   * <code>repeated .proto_java.GetConnectedPeerInfoMessage infos = 1;</code>
   */
  proto_java.GetConnectedPeerInfoMessage getInfos(int index);
  /**
   * <code>repeated .proto_java.GetConnectedPeerInfoMessage infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated .proto_java.GetConnectedPeerInfoMessage infos = 1;</code>
   */
  java.util.List<? extends proto_java.GetConnectedPeerInfoMessageOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <code>repeated .proto_java.GetConnectedPeerInfoMessage infos = 1;</code>
   */
  proto_java.GetConnectedPeerInfoMessageOrBuilder getInfosOrBuilder(
      int index);

  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return The error.
   */
  proto_java.RPCError getError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   */
  proto_java.RPCErrorOrBuilder getErrorOrBuilder();
}
