// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface GetSelectedTipHashResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.GetSelectedTipHashResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string selectedTipHash = 1;</code>
   * @return The selectedTipHash.
   */
  java.lang.String getSelectedTipHash();
  /**
   * <code>string selectedTipHash = 1;</code>
   * @return The bytes for selectedTipHash.
   */
  com.google.protobuf.ByteString
      getSelectedTipHashBytes();

  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   * @return The error.
   */
  proto_java.RPCError getError();
  /**
   * <code>.proto_java.RPCError error = 1000;</code>
   */
  proto_java.RPCErrorOrBuilder getErrorOrBuilder();
}
