// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface GetVirtualSelectedParentChainFromBlockRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.GetVirtualSelectedParentChainFromBlockRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startHash = 1;</code>
   * @return The startHash.
   */
  java.lang.String getStartHash();
  /**
   * <code>string startHash = 1;</code>
   * @return The bytes for startHash.
   */
  com.google.protobuf.ByteString
      getStartHashBytes();

  /**
   * <code>bool includeAcceptedTransactionIds = 2;</code>
   * @return The includeAcceptedTransactionIds.
   */
  boolean getIncludeAcceptedTransactionIds();
}
