// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface IbdBlockLocatorHighestHashMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.IbdBlockLocatorHighestHashMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto_java.Hash highestHash = 1;</code>
   * @return Whether the highestHash field is set.
   */
  boolean hasHighestHash();
  /**
   * <code>.proto_java.Hash highestHash = 1;</code>
   * @return The highestHash.
   */
  proto_java.Hash getHighestHash();
  /**
   * <code>.proto_java.Hash highestHash = 1;</code>
   */
  proto_java.HashOrBuilder getHighestHashOrBuilder();
}
