// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface NetAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.NetAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bytes ip = 3;</code>
   * @return The ip.
   */
  com.google.protobuf.ByteString getIp();

  /**
   * <code>uint32 port = 4;</code>
   * @return The port.
   */
  int getPort();
}
