// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface RpcBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.RpcBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto_java.RpcBlockHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.proto_java.RpcBlockHeader header = 1;</code>
   * @return The header.
   */
  proto_java.RpcBlockHeader getHeader();
  /**
   * <code>.proto_java.RpcBlockHeader header = 1;</code>
   */
  proto_java.RpcBlockHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .proto_java.RpcTransaction transactions = 2;</code>
   */
  java.util.List<proto_java.RpcTransaction> 
      getTransactionsList();
  /**
   * <code>repeated .proto_java.RpcTransaction transactions = 2;</code>
   */
  proto_java.RpcTransaction getTransactions(int index);
  /**
   * <code>repeated .proto_java.RpcTransaction transactions = 2;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .proto_java.RpcTransaction transactions = 2;</code>
   */
  java.util.List<? extends proto_java.RpcTransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .proto_java.RpcTransaction transactions = 2;</code>
   */
  proto_java.RpcTransactionOrBuilder getTransactionsOrBuilder(
      int index);

  /**
   * <code>.proto_java.RpcBlockVerboseData verboseData = 3;</code>
   * @return Whether the verboseData field is set.
   */
  boolean hasVerboseData();
  /**
   * <code>.proto_java.RpcBlockVerboseData verboseData = 3;</code>
   * @return The verboseData.
   */
  proto_java.RpcBlockVerboseData getVerboseData();
  /**
   * <code>.proto_java.RpcBlockVerboseData verboseData = 3;</code>
   */
  proto_java.RpcBlockVerboseDataOrBuilder getVerboseDataOrBuilder();
}
