// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface ShutDownRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.ShutDownRequestMessage)
    com.google.protobuf.MessageOrBuilder {
}
