// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface SubnetworkIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.SubnetworkId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes bytes = 1;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();
}
