// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface TransactionInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.TransactionInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto_java.Outpoint previousOutpoint = 1;</code>
   * @return Whether the previousOutpoint field is set.
   */
  boolean hasPreviousOutpoint();
  /**
   * <code>.proto_java.Outpoint previousOutpoint = 1;</code>
   * @return The previousOutpoint.
   */
  proto_java.Outpoint getPreviousOutpoint();
  /**
   * <code>.proto_java.Outpoint previousOutpoint = 1;</code>
   */
  proto_java.OutpointOrBuilder getPreviousOutpointOrBuilder();

  /**
   * <code>bytes signatureScript = 2;</code>
   * @return The signatureScript.
   */
  com.google.protobuf.ByteString getSignatureScript();

  /**
   * <code>uint64 sequence = 3;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <code>uint32 sigOpCount = 4;</code>
   * @return The sigOpCount.
   */
  int getSigOpCount();
}
