// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package proto_java;

public interface TrustedDataMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.TrustedDataMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto_java.DaaBlockV4 daaWindow = 1;</code>
   */
  java.util.List<proto_java.DaaBlockV4> 
      getDaaWindowList();
  /**
   * <code>repeated .proto_java.DaaBlockV4 daaWindow = 1;</code>
   */
  proto_java.DaaBlockV4 getDaaWindow(int index);
  /**
   * <code>repeated .proto_java.DaaBlockV4 daaWindow = 1;</code>
   */
  int getDaaWindowCount();
  /**
   * <code>repeated .proto_java.DaaBlockV4 daaWindow = 1;</code>
   */
  java.util.List<? extends proto_java.DaaBlockV4OrBuilder> 
      getDaaWindowOrBuilderList();
  /**
   * <code>repeated .proto_java.DaaBlockV4 daaWindow = 1;</code>
   */
  proto_java.DaaBlockV4OrBuilder getDaaWindowOrBuilder(
      int index);

  /**
   * <code>repeated .proto_java.BlockGhostdagDataHashPair ghostdagData = 2;</code>
   */
  java.util.List<proto_java.BlockGhostdagDataHashPair> 
      getGhostdagDataList();
  /**
   * <code>repeated .proto_java.BlockGhostdagDataHashPair ghostdagData = 2;</code>
   */
  proto_java.BlockGhostdagDataHashPair getGhostdagData(int index);
  /**
   * <code>repeated .proto_java.BlockGhostdagDataHashPair ghostdagData = 2;</code>
   */
  int getGhostdagDataCount();
  /**
   * <code>repeated .proto_java.BlockGhostdagDataHashPair ghostdagData = 2;</code>
   */
  java.util.List<? extends proto_java.BlockGhostdagDataHashPairOrBuilder> 
      getGhostdagDataOrBuilderList();
  /**
   * <code>repeated .proto_java.BlockGhostdagDataHashPair ghostdagData = 2;</code>
   */
  proto_java.BlockGhostdagDataHashPairOrBuilder getGhostdagDataOrBuilder(
      int index);
}
