// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

/**
 * <pre>
 * UtxosChangedNotificationMessage is sent whenever the UTXO index had been updated.
 * See: NotifyUtxosChangedRequestMessage
 * </pre>
 *
 * Protobuf type {@code proto_java.UtxosChangedNotificationMessage}
 */
public final class UtxosChangedNotificationMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto_java.UtxosChangedNotificationMessage)
    UtxosChangedNotificationMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UtxosChangedNotificationMessage.newBuilder() to construct.
  private UtxosChangedNotificationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UtxosChangedNotificationMessage() {
    added_ = java.util.Collections.emptyList();
    removed_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UtxosChangedNotificationMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UtxosChangedNotificationMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              added_ = new java.util.ArrayList<proto_java.UtxosByAddressesEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            added_.add(
                input.readMessage(proto_java.UtxosByAddressesEntry.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              removed_ = new java.util.ArrayList<proto_java.UtxosByAddressesEntry>();
              mutable_bitField0_ |= 0x00000002;
            }
            removed_.add(
                input.readMessage(proto_java.UtxosByAddressesEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        added_ = java.util.Collections.unmodifiableList(added_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        removed_ = java.util.Collections.unmodifiableList(removed_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto_java.Rpc.internal_static_org_example_grpc_UtxosChangedNotificationMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto_java.Rpc.internal_static_org_example_grpc_UtxosChangedNotificationMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto_java.UtxosChangedNotificationMessage.class, proto_java.UtxosChangedNotificationMessage.Builder.class);
  }

  public static final int ADDED_FIELD_NUMBER = 1;
  private java.util.List<proto_java.UtxosByAddressesEntry> added_;
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto_java.UtxosByAddressesEntry> getAddedList() {
    return added_;
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto_java.UtxosByAddressesEntryOrBuilder> 
      getAddedOrBuilderList() {
    return added_;
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
   */
  @java.lang.Override
  public int getAddedCount() {
    return added_.size();
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
   */
  @java.lang.Override
  public proto_java.UtxosByAddressesEntry getAdded(int index) {
    return added_.get(index);
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
   */
  @java.lang.Override
  public proto_java.UtxosByAddressesEntryOrBuilder getAddedOrBuilder(
      int index) {
    return added_.get(index);
  }

  public static final int REMOVED_FIELD_NUMBER = 2;
  private java.util.List<proto_java.UtxosByAddressesEntry> removed_;
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
   */
  @java.lang.Override
  public java.util.List<proto_java.UtxosByAddressesEntry> getRemovedList() {
    return removed_;
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto_java.UtxosByAddressesEntryOrBuilder> 
      getRemovedOrBuilderList() {
    return removed_;
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
   */
  @java.lang.Override
  public int getRemovedCount() {
    return removed_.size();
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
   */
  @java.lang.Override
  public proto_java.UtxosByAddressesEntry getRemoved(int index) {
    return removed_.get(index);
  }
  /**
   * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
   */
  @java.lang.Override
  public proto_java.UtxosByAddressesEntryOrBuilder getRemovedOrBuilder(
      int index) {
    return removed_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < added_.size(); i++) {
      output.writeMessage(1, added_.get(i));
    }
    for (int i = 0; i < removed_.size(); i++) {
      output.writeMessage(2, removed_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < added_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, added_.get(i));
    }
    for (int i = 0; i < removed_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, removed_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto_java.UtxosChangedNotificationMessage)) {
      return super.equals(obj);
    }
    proto_java.UtxosChangedNotificationMessage other = (proto_java.UtxosChangedNotificationMessage) obj;

    if (!getAddedList()
        .equals(other.getAddedList())) return false;
    if (!getRemovedList()
        .equals(other.getRemovedList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAddedCount() > 0) {
      hash = (37 * hash) + ADDED_FIELD_NUMBER;
      hash = (53 * hash) + getAddedList().hashCode();
    }
    if (getRemovedCount() > 0) {
      hash = (37 * hash) + REMOVED_FIELD_NUMBER;
      hash = (53 * hash) + getRemovedList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_java.UtxosChangedNotificationMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto_java.UtxosChangedNotificationMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_java.UtxosChangedNotificationMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto_java.UtxosChangedNotificationMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * UtxosChangedNotificationMessage is sent whenever the UTXO index had been updated.
   * See: NotifyUtxosChangedRequestMessage
   * </pre>
   *
   * Protobuf type {@code proto_java.UtxosChangedNotificationMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto_java.UtxosChangedNotificationMessage)
      proto_java.UtxosChangedNotificationMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_java.Rpc.internal_static_org_example_grpc_UtxosChangedNotificationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_java.Rpc.internal_static_org_example_grpc_UtxosChangedNotificationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_java.UtxosChangedNotificationMessage.class, proto_java.UtxosChangedNotificationMessage.Builder.class);
    }

    // Construct using proto_java.UtxosChangedNotificationMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddedFieldBuilder();
        getRemovedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (addedBuilder_ == null) {
        added_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        addedBuilder_.clear();
      }
      if (removedBuilder_ == null) {
        removed_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        removedBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto_java.Rpc.internal_static_org_example_grpc_UtxosChangedNotificationMessage_descriptor;
    }

    @java.lang.Override
    public proto_java.UtxosChangedNotificationMessage getDefaultInstanceForType() {
      return proto_java.UtxosChangedNotificationMessage.getDefaultInstance();
    }

    @java.lang.Override
    public proto_java.UtxosChangedNotificationMessage build() {
      proto_java.UtxosChangedNotificationMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto_java.UtxosChangedNotificationMessage buildPartial() {
      proto_java.UtxosChangedNotificationMessage result = new proto_java.UtxosChangedNotificationMessage(this);
      int from_bitField0_ = bitField0_;
      if (addedBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          added_ = java.util.Collections.unmodifiableList(added_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.added_ = added_;
      } else {
        result.added_ = addedBuilder_.build();
      }
      if (removedBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          removed_ = java.util.Collections.unmodifiableList(removed_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.removed_ = removed_;
      } else {
        result.removed_ = removedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto_java.UtxosChangedNotificationMessage) {
        return mergeFrom((proto_java.UtxosChangedNotificationMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto_java.UtxosChangedNotificationMessage other) {
      if (other == proto_java.UtxosChangedNotificationMessage.getDefaultInstance()) return this;
      if (addedBuilder_ == null) {
        if (!other.added_.isEmpty()) {
          if (added_.isEmpty()) {
            added_ = other.added_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddedIsMutable();
            added_.addAll(other.added_);
          }
          onChanged();
        }
      } else {
        if (!other.added_.isEmpty()) {
          if (addedBuilder_.isEmpty()) {
            addedBuilder_.dispose();
            addedBuilder_ = null;
            added_ = other.added_;
            bitField0_ = (bitField0_ & ~0x00000001);
            addedBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddedFieldBuilder() : null;
          } else {
            addedBuilder_.addAllMessages(other.added_);
          }
        }
      }
      if (removedBuilder_ == null) {
        if (!other.removed_.isEmpty()) {
          if (removed_.isEmpty()) {
            removed_ = other.removed_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRemovedIsMutable();
            removed_.addAll(other.removed_);
          }
          onChanged();
        }
      } else {
        if (!other.removed_.isEmpty()) {
          if (removedBuilder_.isEmpty()) {
            removedBuilder_.dispose();
            removedBuilder_ = null;
            removed_ = other.removed_;
            bitField0_ = (bitField0_ & ~0x00000002);
            removedBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRemovedFieldBuilder() : null;
          } else {
            removedBuilder_.addAllMessages(other.removed_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto_java.UtxosChangedNotificationMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto_java.UtxosChangedNotificationMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proto_java.UtxosByAddressesEntry> added_ =
      java.util.Collections.emptyList();
    private void ensureAddedIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        added_ = new java.util.ArrayList<proto_java.UtxosByAddressesEntry>(added_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder> addedBuilder_;

    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public java.util.List<proto_java.UtxosByAddressesEntry> getAddedList() {
      if (addedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(added_);
      } else {
        return addedBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public int getAddedCount() {
      if (addedBuilder_ == null) {
        return added_.size();
      } else {
        return addedBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public proto_java.UtxosByAddressesEntry getAdded(int index) {
      if (addedBuilder_ == null) {
        return added_.get(index);
      } else {
        return addedBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder setAdded(
        int index, proto_java.UtxosByAddressesEntry value) {
      if (addedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedIsMutable();
        added_.set(index, value);
        onChanged();
      } else {
        addedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder setAdded(
        int index, proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (addedBuilder_ == null) {
        ensureAddedIsMutable();
        added_.set(index, builderForValue.build());
        onChanged();
      } else {
        addedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder addAdded(proto_java.UtxosByAddressesEntry value) {
      if (addedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedIsMutable();
        added_.add(value);
        onChanged();
      } else {
        addedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder addAdded(
        int index, proto_java.UtxosByAddressesEntry value) {
      if (addedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedIsMutable();
        added_.add(index, value);
        onChanged();
      } else {
        addedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder addAdded(
        proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (addedBuilder_ == null) {
        ensureAddedIsMutable();
        added_.add(builderForValue.build());
        onChanged();
      } else {
        addedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder addAdded(
        int index, proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (addedBuilder_ == null) {
        ensureAddedIsMutable();
        added_.add(index, builderForValue.build());
        onChanged();
      } else {
        addedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder addAllAdded(
        java.lang.Iterable<? extends proto_java.UtxosByAddressesEntry> values) {
      if (addedBuilder_ == null) {
        ensureAddedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, added_);
        onChanged();
      } else {
        addedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder clearAdded() {
      if (addedBuilder_ == null) {
        added_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        addedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public Builder removeAdded(int index) {
      if (addedBuilder_ == null) {
        ensureAddedIsMutable();
        added_.remove(index);
        onChanged();
      } else {
        addedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder getAddedBuilder(
        int index) {
      return getAddedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public proto_java.UtxosByAddressesEntryOrBuilder getAddedOrBuilder(
        int index) {
      if (addedBuilder_ == null) {
        return added_.get(index);  } else {
        return addedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public java.util.List<? extends proto_java.UtxosByAddressesEntryOrBuilder> 
         getAddedOrBuilderList() {
      if (addedBuilder_ != null) {
        return addedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(added_);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder addAddedBuilder() {
      return getAddedFieldBuilder().addBuilder(
          proto_java.UtxosByAddressesEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder addAddedBuilder(
        int index) {
      return getAddedFieldBuilder().addBuilder(
          index, proto_java.UtxosByAddressesEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry added = 1;</code>
     */
    public java.util.List<proto_java.UtxosByAddressesEntry.Builder> 
         getAddedBuilderList() {
      return getAddedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder> 
        getAddedFieldBuilder() {
      if (addedBuilder_ == null) {
        addedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder>(
                added_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        added_ = null;
      }
      return addedBuilder_;
    }

    private java.util.List<proto_java.UtxosByAddressesEntry> removed_ =
      java.util.Collections.emptyList();
    private void ensureRemovedIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        removed_ = new java.util.ArrayList<proto_java.UtxosByAddressesEntry>(removed_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder> removedBuilder_;

    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public java.util.List<proto_java.UtxosByAddressesEntry> getRemovedList() {
      if (removedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(removed_);
      } else {
        return removedBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public int getRemovedCount() {
      if (removedBuilder_ == null) {
        return removed_.size();
      } else {
        return removedBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public proto_java.UtxosByAddressesEntry getRemoved(int index) {
      if (removedBuilder_ == null) {
        return removed_.get(index);
      } else {
        return removedBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder setRemoved(
        int index, proto_java.UtxosByAddressesEntry value) {
      if (removedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemovedIsMutable();
        removed_.set(index, value);
        onChanged();
      } else {
        removedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder setRemoved(
        int index, proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (removedBuilder_ == null) {
        ensureRemovedIsMutable();
        removed_.set(index, builderForValue.build());
        onChanged();
      } else {
        removedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder addRemoved(proto_java.UtxosByAddressesEntry value) {
      if (removedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemovedIsMutable();
        removed_.add(value);
        onChanged();
      } else {
        removedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder addRemoved(
        int index, proto_java.UtxosByAddressesEntry value) {
      if (removedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemovedIsMutable();
        removed_.add(index, value);
        onChanged();
      } else {
        removedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder addRemoved(
        proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (removedBuilder_ == null) {
        ensureRemovedIsMutable();
        removed_.add(builderForValue.build());
        onChanged();
      } else {
        removedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder addRemoved(
        int index, proto_java.UtxosByAddressesEntry.Builder builderForValue) {
      if (removedBuilder_ == null) {
        ensureRemovedIsMutable();
        removed_.add(index, builderForValue.build());
        onChanged();
      } else {
        removedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder addAllRemoved(
        java.lang.Iterable<? extends proto_java.UtxosByAddressesEntry> values) {
      if (removedBuilder_ == null) {
        ensureRemovedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, removed_);
        onChanged();
      } else {
        removedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder clearRemoved() {
      if (removedBuilder_ == null) {
        removed_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        removedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public Builder removeRemoved(int index) {
      if (removedBuilder_ == null) {
        ensureRemovedIsMutable();
        removed_.remove(index);
        onChanged();
      } else {
        removedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder getRemovedBuilder(
        int index) {
      return getRemovedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public proto_java.UtxosByAddressesEntryOrBuilder getRemovedOrBuilder(
        int index) {
      if (removedBuilder_ == null) {
        return removed_.get(index);  } else {
        return removedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public java.util.List<? extends proto_java.UtxosByAddressesEntryOrBuilder> 
         getRemovedOrBuilderList() {
      if (removedBuilder_ != null) {
        return removedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(removed_);
      }
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder addRemovedBuilder() {
      return getRemovedFieldBuilder().addBuilder(
          proto_java.UtxosByAddressesEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public proto_java.UtxosByAddressesEntry.Builder addRemovedBuilder(
        int index) {
      return getRemovedFieldBuilder().addBuilder(
          index, proto_java.UtxosByAddressesEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .proto_java.UtxosByAddressesEntry removed = 2;</code>
     */
    public java.util.List<proto_java.UtxosByAddressesEntry.Builder> 
         getRemovedBuilderList() {
      return getRemovedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder> 
        getRemovedFieldBuilder() {
      if (removedBuilder_ == null) {
        removedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto_java.UtxosByAddressesEntry, proto_java.UtxosByAddressesEntry.Builder, proto_java.UtxosByAddressesEntryOrBuilder>(
                removed_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        removed_ = null;
      }
      return removedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto_java.UtxosChangedNotificationMessage)
  }

  // @@protoc_insertion_point(class_scope:proto_java.UtxosChangedNotificationMessage)
  private static final proto_java.UtxosChangedNotificationMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto_java.UtxosChangedNotificationMessage();
  }

  public static proto_java.UtxosChangedNotificationMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UtxosChangedNotificationMessage>
      PARSER = new com.google.protobuf.AbstractParser<UtxosChangedNotificationMessage>() {
    @java.lang.Override
    public UtxosChangedNotificationMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UtxosChangedNotificationMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UtxosChangedNotificationMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UtxosChangedNotificationMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto_java.UtxosChangedNotificationMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

