// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package proto_java;

public interface VirtualSelectedParentBlueScoreChangedNotificationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto_java.VirtualSelectedParentBlueScoreChangedNotificationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 virtualSelectedParentBlueScore = 1;</code>
   * @return The virtualSelectedParentBlueScore.
   */
  long getVirtualSelectedParentBlueScore();
}
