// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package protowire;

public interface BlockWithTrustedDataMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.BlockWithTrustedDataMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protowire.BlockMessage block = 1;</code>
   * @return Whether the block field is set.
   */
  boolean hasBlock();
  /**
   * <code>.protowire.BlockMessage block = 1;</code>
   * @return The block.
   */
  protowire.BlockMessage getBlock();
  /**
   * <code>.protowire.BlockMessage block = 1;</code>
   */
  protowire.BlockMessageOrBuilder getBlockOrBuilder();

  /**
   * <code>uint64 daaScore = 2;</code>
   * @return The daaScore.
   */
  long getDaaScore();

  /**
   * <code>repeated .protowire.DaaBlock daaWindow = 3;</code>
   */
  java.util.List<protowire.DaaBlock> 
      getDaaWindowList();
  /**
   * <code>repeated .protowire.DaaBlock daaWindow = 3;</code>
   */
  protowire.DaaBlock getDaaWindow(int index);
  /**
   * <code>repeated .protowire.DaaBlock daaWindow = 3;</code>
   */
  int getDaaWindowCount();
  /**
   * <code>repeated .protowire.DaaBlock daaWindow = 3;</code>
   */
  java.util.List<? extends protowire.DaaBlockOrBuilder> 
      getDaaWindowOrBuilderList();
  /**
   * <code>repeated .protowire.DaaBlock daaWindow = 3;</code>
   */
  protowire.DaaBlockOrBuilder getDaaWindowOrBuilder(
      int index);

  /**
   * <code>repeated .protowire.BlockGhostdagDataHashPair ghostdagData = 4;</code>
   */
  java.util.List<protowire.BlockGhostdagDataHashPair> 
      getGhostdagDataList();
  /**
   * <code>repeated .protowire.BlockGhostdagDataHashPair ghostdagData = 4;</code>
   */
  protowire.BlockGhostdagDataHashPair getGhostdagData(int index);
  /**
   * <code>repeated .protowire.BlockGhostdagDataHashPair ghostdagData = 4;</code>
   */
  int getGhostdagDataCount();
  /**
   * <code>repeated .protowire.BlockGhostdagDataHashPair ghostdagData = 4;</code>
   */
  java.util.List<? extends protowire.BlockGhostdagDataHashPairOrBuilder> 
      getGhostdagDataOrBuilderList();
  /**
   * <code>repeated .protowire.BlockGhostdagDataHashPair ghostdagData = 4;</code>
   */
  protowire.BlockGhostdagDataHashPairOrBuilder getGhostdagDataOrBuilder(
      int index);
}
