// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package protowire;

public interface BlockHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.BlockHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .protowire.BlockLevelParents parents = 12;</code>
   */
  java.util.List<protowire.BlockLevelParents> 
      getParentsList();
  /**
   * <code>repeated .protowire.BlockLevelParents parents = 12;</code>
   */
  protowire.BlockLevelParents getParents(int index);
  /**
   * <code>repeated .protowire.BlockLevelParents parents = 12;</code>
   */
  int getParentsCount();
  /**
   * <code>repeated .protowire.BlockLevelParents parents = 12;</code>
   */
  java.util.List<? extends protowire.BlockLevelParentsOrBuilder> 
      getParentsOrBuilderList();
  /**
   * <code>repeated .protowire.BlockLevelParents parents = 12;</code>
   */
  protowire.BlockLevelParentsOrBuilder getParentsOrBuilder(
      int index);

  /**
   * <code>.protowire.Hash hashMerkleRoot = 3;</code>
   * @return Whether the hashMerkleRoot field is set.
   */
  boolean hasHashMerkleRoot();
  /**
   * <code>.protowire.Hash hashMerkleRoot = 3;</code>
   * @return The hashMerkleRoot.
   */
  protowire.Hash getHashMerkleRoot();
  /**
   * <code>.protowire.Hash hashMerkleRoot = 3;</code>
   */
  protowire.HashOrBuilder getHashMerkleRootOrBuilder();

  /**
   * <code>.protowire.Hash acceptedIdMerkleRoot = 4;</code>
   * @return Whether the acceptedIdMerkleRoot field is set.
   */
  boolean hasAcceptedIdMerkleRoot();
  /**
   * <code>.protowire.Hash acceptedIdMerkleRoot = 4;</code>
   * @return The acceptedIdMerkleRoot.
   */
  protowire.Hash getAcceptedIdMerkleRoot();
  /**
   * <code>.protowire.Hash acceptedIdMerkleRoot = 4;</code>
   */
  protowire.HashOrBuilder getAcceptedIdMerkleRootOrBuilder();

  /**
   * <code>.protowire.Hash utxoCommitment = 5;</code>
   * @return Whether the utxoCommitment field is set.
   */
  boolean hasUtxoCommitment();
  /**
   * <code>.protowire.Hash utxoCommitment = 5;</code>
   * @return The utxoCommitment.
   */
  protowire.Hash getUtxoCommitment();
  /**
   * <code>.protowire.Hash utxoCommitment = 5;</code>
   */
  protowire.HashOrBuilder getUtxoCommitmentOrBuilder();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>uint32 bits = 7;</code>
   * @return The bits.
   */
  int getBits();

  /**
   * <code>uint64 nonce = 8;</code>
   * @return The nonce.
   */
  long getNonce();

  /**
   * <code>uint64 daaScore = 9;</code>
   * @return The daaScore.
   */
  long getDaaScore();

  /**
   * <code>bytes blueWork = 10;</code>
   * @return The blueWork.
   */
  com.google.protobuf.ByteString getBlueWork();

  /**
   * <code>.protowire.Hash pruningPoint = 14;</code>
   * @return Whether the pruningPoint field is set.
   */
  boolean hasPruningPoint();
  /**
   * <code>.protowire.Hash pruningPoint = 14;</code>
   * @return The pruningPoint.
   */
  protowire.Hash getPruningPoint();
  /**
   * <code>.protowire.Hash pruningPoint = 14;</code>
   */
  protowire.HashOrBuilder getPruningPointOrBuilder();

  /**
   * <code>uint64 blueScore = 13;</code>
   * @return The blueScore.
   */
  long getBlueScore();
}
