// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package protowire;

public interface DaaBlockV4OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.DaaBlockV4)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protowire.BlockHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.protowire.BlockHeader header = 1;</code>
   * @return The header.
   */
  protowire.BlockHeader getHeader();
  /**
   * <code>.protowire.BlockHeader header = 1;</code>
   */
  protowire.BlockHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>.protowire.GhostdagData ghostdagData = 2;</code>
   * @return Whether the ghostdagData field is set.
   */
  boolean hasGhostdagData();
  /**
   * <code>.protowire.GhostdagData ghostdagData = 2;</code>
   * @return The ghostdagData.
   */
  protowire.GhostdagData getGhostdagData();
  /**
   * <code>.protowire.GhostdagData ghostdagData = 2;</code>
   */
  protowire.GhostdagDataOrBuilder getGhostdagDataOrBuilder();
}
