// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface GetBlockCountRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.GetBlockCountRequestMessage)
    com.google.protobuf.MessageOrBuilder {
}
