// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface GetHeadersRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.GetHeadersRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startHash = 1;</code>
   * @return The startHash.
   */
  java.lang.String getStartHash();
  /**
   * <code>string startHash = 1;</code>
   * @return The bytes for startHash.
   */
  com.google.protobuf.ByteString
      getStartHashBytes();

  /**
   * <code>uint64 limit = 2;</code>
   * @return The limit.
   */
  long getLimit();

  /**
   * <code>bool isAscending = 3;</code>
   * @return The isAscending.
   */
  boolean getIsAscending();
}
