// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface GetMempoolEntryResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.GetMempoolEntryResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protowire.MempoolEntry entry = 1;</code>
   * @return Whether the entry field is set.
   */
  boolean hasEntry();
  /**
   * <code>.protowire.MempoolEntry entry = 1;</code>
   * @return The entry.
   */
  protowire.MempoolEntry getEntry();
  /**
   * <code>.protowire.MempoolEntry entry = 1;</code>
   */
  protowire.MempoolEntryOrBuilder getEntryOrBuilder();

  /**
   * <code>.protowire.RPCError error = 1000;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.protowire.RPCError error = 1000;</code>
   * @return The error.
   */
  protowire.RPCError getError();
  /**
   * <code>.protowire.RPCError error = 1000;</code>
   */
  protowire.RPCErrorOrBuilder getErrorOrBuilder();
}
