// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface GetPeerAddressesResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.GetPeerAddressesResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage addresses = 1;</code>
   */
  java.util.List<protowire.GetPeerAddressesKnownAddressMessage> 
      getAddressesList();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage addresses = 1;</code>
   */
  protowire.GetPeerAddressesKnownAddressMessage getAddresses(int index);
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage addresses = 1;</code>
   */
  int getAddressesCount();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage addresses = 1;</code>
   */
  java.util.List<? extends protowire.GetPeerAddressesKnownAddressMessageOrBuilder> 
      getAddressesOrBuilderList();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage addresses = 1;</code>
   */
  protowire.GetPeerAddressesKnownAddressMessageOrBuilder getAddressesOrBuilder(
      int index);

  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage bannedAddresses = 2;</code>
   */
  java.util.List<protowire.GetPeerAddressesKnownAddressMessage> 
      getBannedAddressesList();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage bannedAddresses = 2;</code>
   */
  protowire.GetPeerAddressesKnownAddressMessage getBannedAddresses(int index);
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage bannedAddresses = 2;</code>
   */
  int getBannedAddressesCount();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage bannedAddresses = 2;</code>
   */
  java.util.List<? extends protowire.GetPeerAddressesKnownAddressMessageOrBuilder> 
      getBannedAddressesOrBuilderList();
  /**
   * <code>repeated .protowire.GetPeerAddressesKnownAddressMessage bannedAddresses = 2;</code>
   */
  protowire.GetPeerAddressesKnownAddressMessageOrBuilder getBannedAddressesOrBuilder(
      int index);

  /**
   * <code>.protowire.RPCError error = 1000;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.protowire.RPCError error = 1000;</code>
   * @return The error.
   */
  protowire.RPCError getError();
  /**
   * <code>.protowire.RPCError error = 1000;</code>
   */
  protowire.RPCErrorOrBuilder getErrorOrBuilder();
}
