// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface GetPeerAddressesKnownAddressMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.GetPeerAddressesKnownAddressMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Addr = 1;</code>
   * @return The addr.
   */
  java.lang.String getAddr();
  /**
   * <code>string Addr = 1;</code>
   * @return The bytes for addr.
   */
  com.google.protobuf.ByteString
      getAddrBytes();
}
