// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2p.proto

package protowire;

public interface IbdBlockLocatorMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.IbdBlockLocatorMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protowire.Hash targetHash = 1;</code>
   * @return Whether the targetHash field is set.
   */
  boolean hasTargetHash();
  /**
   * <code>.protowire.Hash targetHash = 1;</code>
   * @return The targetHash.
   */
  protowire.Hash getTargetHash();
  /**
   * <code>.protowire.Hash targetHash = 1;</code>
   */
  protowire.HashOrBuilder getTargetHashOrBuilder();

  /**
   * <code>repeated .protowire.Hash blockLocatorHashes = 2;</code>
   */
  java.util.List<protowire.Hash> 
      getBlockLocatorHashesList();
  /**
   * <code>repeated .protowire.Hash blockLocatorHashes = 2;</code>
   */
  protowire.Hash getBlockLocatorHashes(int index);
  /**
   * <code>repeated .protowire.Hash blockLocatorHashes = 2;</code>
   */
  int getBlockLocatorHashesCount();
  /**
   * <code>repeated .protowire.Hash blockLocatorHashes = 2;</code>
   */
  java.util.List<? extends protowire.HashOrBuilder> 
      getBlockLocatorHashesOrBuilderList();
  /**
   * <code>repeated .protowire.Hash blockLocatorHashes = 2;</code>
   */
  protowire.HashOrBuilder getBlockLocatorHashesOrBuilder(
      int index);
}
