// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface PruningPointUTXOSetOverrideNotificationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.PruningPointUTXOSetOverrideNotificationMessage)
    com.google.protobuf.MessageOrBuilder {
}
