// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

/**
 * Protobuf type {@code protowire.RpcBlockHeader}
 */
public final class RpcBlockHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protowire.RpcBlockHeader)
    RpcBlockHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RpcBlockHeader.newBuilder() to construct.
  private RpcBlockHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcBlockHeader() {
    parents_ = java.util.Collections.emptyList();
    hashMerkleRoot_ = "";
    acceptedIdMerkleRoot_ = "";
    utxoCommitment_ = "";
    blueWork_ = "";
    pruningPoint_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RpcBlockHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RpcBlockHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readUInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            hashMerkleRoot_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            acceptedIdMerkleRoot_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            utxoCommitment_ = s;
            break;
          }
          case 48: {

            timestamp_ = input.readInt64();
            break;
          }
          case 56: {

            bits_ = input.readUInt32();
            break;
          }
          case 64: {

            nonce_ = input.readUInt64();
            break;
          }
          case 72: {

            daaScore_ = input.readUInt64();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            blueWork_ = s;
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              parents_ = new java.util.ArrayList<protowire.RpcBlockLevelParents>();
              mutable_bitField0_ |= 0x00000001;
            }
            parents_.add(
                input.readMessage(protowire.RpcBlockLevelParents.parser(), extensionRegistry));
            break;
          }
          case 104: {

            blueScore_ = input.readUInt64();
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            pruningPoint_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        parents_ = java.util.Collections.unmodifiableList(parents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protowire.Rpc.internal_static_protowire_RpcBlockHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protowire.Rpc.internal_static_protowire_RpcBlockHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protowire.RpcBlockHeader.class, protowire.RpcBlockHeader.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int PARENTS_FIELD_NUMBER = 12;
  private java.util.List<protowire.RpcBlockLevelParents> parents_;
  /**
   * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
   */
  @java.lang.Override
  public java.util.List<protowire.RpcBlockLevelParents> getParentsList() {
    return parents_;
  }
  /**
   * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protowire.RpcBlockLevelParentsOrBuilder> 
      getParentsOrBuilderList() {
    return parents_;
  }
  /**
   * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
   */
  @java.lang.Override
  public int getParentsCount() {
    return parents_.size();
  }
  /**
   * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
   */
  @java.lang.Override
  public protowire.RpcBlockLevelParents getParents(int index) {
    return parents_.get(index);
  }
  /**
   * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
   */
  @java.lang.Override
  public protowire.RpcBlockLevelParentsOrBuilder getParentsOrBuilder(
      int index) {
    return parents_.get(index);
  }

  public static final int HASHMERKLEROOT_FIELD_NUMBER = 3;
  private volatile java.lang.Object hashMerkleRoot_;
  /**
   * <code>string hashMerkleRoot = 3;</code>
   * @return The hashMerkleRoot.
   */
  @java.lang.Override
  public java.lang.String getHashMerkleRoot() {
    java.lang.Object ref = hashMerkleRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hashMerkleRoot_ = s;
      return s;
    }
  }
  /**
   * <code>string hashMerkleRoot = 3;</code>
   * @return The bytes for hashMerkleRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHashMerkleRootBytes() {
    java.lang.Object ref = hashMerkleRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hashMerkleRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCEPTEDIDMERKLEROOT_FIELD_NUMBER = 4;
  private volatile java.lang.Object acceptedIdMerkleRoot_;
  /**
   * <code>string acceptedIdMerkleRoot = 4;</code>
   * @return The acceptedIdMerkleRoot.
   */
  @java.lang.Override
  public java.lang.String getAcceptedIdMerkleRoot() {
    java.lang.Object ref = acceptedIdMerkleRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      acceptedIdMerkleRoot_ = s;
      return s;
    }
  }
  /**
   * <code>string acceptedIdMerkleRoot = 4;</code>
   * @return The bytes for acceptedIdMerkleRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAcceptedIdMerkleRootBytes() {
    java.lang.Object ref = acceptedIdMerkleRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      acceptedIdMerkleRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTXOCOMMITMENT_FIELD_NUMBER = 5;
  private volatile java.lang.Object utxoCommitment_;
  /**
   * <code>string utxoCommitment = 5;</code>
   * @return The utxoCommitment.
   */
  @java.lang.Override
  public java.lang.String getUtxoCommitment() {
    java.lang.Object ref = utxoCommitment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utxoCommitment_ = s;
      return s;
    }
  }
  /**
   * <code>string utxoCommitment = 5;</code>
   * @return The bytes for utxoCommitment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtxoCommitmentBytes() {
    java.lang.Object ref = utxoCommitment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utxoCommitment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int BITS_FIELD_NUMBER = 7;
  private int bits_;
  /**
   * <code>uint32 bits = 7;</code>
   * @return The bits.
   */
  @java.lang.Override
  public int getBits() {
    return bits_;
  }

  public static final int NONCE_FIELD_NUMBER = 8;
  private long nonce_;
  /**
   * <code>uint64 nonce = 8;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public long getNonce() {
    return nonce_;
  }

  public static final int DAASCORE_FIELD_NUMBER = 9;
  private long daaScore_;
  /**
   * <code>uint64 daaScore = 9;</code>
   * @return The daaScore.
   */
  @java.lang.Override
  public long getDaaScore() {
    return daaScore_;
  }

  public static final int BLUEWORK_FIELD_NUMBER = 10;
  private volatile java.lang.Object blueWork_;
  /**
   * <code>string blueWork = 10;</code>
   * @return The blueWork.
   */
  @java.lang.Override
  public java.lang.String getBlueWork() {
    java.lang.Object ref = blueWork_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blueWork_ = s;
      return s;
    }
  }
  /**
   * <code>string blueWork = 10;</code>
   * @return The bytes for blueWork.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlueWorkBytes() {
    java.lang.Object ref = blueWork_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blueWork_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRUNINGPOINT_FIELD_NUMBER = 14;
  private volatile java.lang.Object pruningPoint_;
  /**
   * <code>string pruningPoint = 14;</code>
   * @return The pruningPoint.
   */
  @java.lang.Override
  public java.lang.String getPruningPoint() {
    java.lang.Object ref = pruningPoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pruningPoint_ = s;
      return s;
    }
  }
  /**
   * <code>string pruningPoint = 14;</code>
   * @return The bytes for pruningPoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPruningPointBytes() {
    java.lang.Object ref = pruningPoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pruningPoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLUESCORE_FIELD_NUMBER = 13;
  private long blueScore_;
  /**
   * <code>uint64 blueScore = 13;</code>
   * @return The blueScore.
   */
  @java.lang.Override
  public long getBlueScore() {
    return blueScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeUInt32(1, version_);
    }
    if (!getHashMerkleRootBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hashMerkleRoot_);
    }
    if (!getAcceptedIdMerkleRootBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, acceptedIdMerkleRoot_);
    }
    if (!getUtxoCommitmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, utxoCommitment_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (bits_ != 0) {
      output.writeUInt32(7, bits_);
    }
    if (nonce_ != 0L) {
      output.writeUInt64(8, nonce_);
    }
    if (daaScore_ != 0L) {
      output.writeUInt64(9, daaScore_);
    }
    if (!getBlueWorkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, blueWork_);
    }
    for (int i = 0; i < parents_.size(); i++) {
      output.writeMessage(12, parents_.get(i));
    }
    if (blueScore_ != 0L) {
      output.writeUInt64(13, blueScore_);
    }
    if (!getPruningPointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, pruningPoint_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, version_);
    }
    if (!getHashMerkleRootBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hashMerkleRoot_);
    }
    if (!getAcceptedIdMerkleRootBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, acceptedIdMerkleRoot_);
    }
    if (!getUtxoCommitmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, utxoCommitment_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (bits_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, bits_);
    }
    if (nonce_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, nonce_);
    }
    if (daaScore_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, daaScore_);
    }
    if (!getBlueWorkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, blueWork_);
    }
    for (int i = 0; i < parents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, parents_.get(i));
    }
    if (blueScore_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, blueScore_);
    }
    if (!getPruningPointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, pruningPoint_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protowire.RpcBlockHeader)) {
      return super.equals(obj);
    }
    protowire.RpcBlockHeader other = (protowire.RpcBlockHeader) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getParentsList()
        .equals(other.getParentsList())) return false;
    if (!getHashMerkleRoot()
        .equals(other.getHashMerkleRoot())) return false;
    if (!getAcceptedIdMerkleRoot()
        .equals(other.getAcceptedIdMerkleRoot())) return false;
    if (!getUtxoCommitment()
        .equals(other.getUtxoCommitment())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getBits()
        != other.getBits()) return false;
    if (getNonce()
        != other.getNonce()) return false;
    if (getDaaScore()
        != other.getDaaScore()) return false;
    if (!getBlueWork()
        .equals(other.getBlueWork())) return false;
    if (!getPruningPoint()
        .equals(other.getPruningPoint())) return false;
    if (getBlueScore()
        != other.getBlueScore()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getParentsCount() > 0) {
      hash = (37 * hash) + PARENTS_FIELD_NUMBER;
      hash = (53 * hash) + getParentsList().hashCode();
    }
    hash = (37 * hash) + HASHMERKLEROOT_FIELD_NUMBER;
    hash = (53 * hash) + getHashMerkleRoot().hashCode();
    hash = (37 * hash) + ACCEPTEDIDMERKLEROOT_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptedIdMerkleRoot().hashCode();
    hash = (37 * hash) + UTXOCOMMITMENT_FIELD_NUMBER;
    hash = (53 * hash) + getUtxoCommitment().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + BITS_FIELD_NUMBER;
    hash = (53 * hash) + getBits();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNonce());
    hash = (37 * hash) + DAASCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDaaScore());
    hash = (37 * hash) + BLUEWORK_FIELD_NUMBER;
    hash = (53 * hash) + getBlueWork().hashCode();
    hash = (37 * hash) + PRUNINGPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getPruningPoint().hashCode();
    hash = (37 * hash) + BLUESCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlueScore());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protowire.RpcBlockHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protowire.RpcBlockHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protowire.RpcBlockHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protowire.RpcBlockHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protowire.RpcBlockHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protowire.RpcBlockHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protowire.RpcBlockHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protowire.RpcBlockHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protowire.RpcBlockHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protowire.RpcBlockHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protowire.RpcBlockHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protowire.RpcBlockHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protowire.RpcBlockHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protowire.RpcBlockHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protowire.RpcBlockHeader)
      protowire.RpcBlockHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protowire.Rpc.internal_static_protowire_RpcBlockHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protowire.Rpc.internal_static_protowire_RpcBlockHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protowire.RpcBlockHeader.class, protowire.RpcBlockHeader.Builder.class);
    }

    // Construct using protowire.RpcBlockHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getParentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (parentsBuilder_ == null) {
        parents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        parentsBuilder_.clear();
      }
      hashMerkleRoot_ = "";

      acceptedIdMerkleRoot_ = "";

      utxoCommitment_ = "";

      timestamp_ = 0L;

      bits_ = 0;

      nonce_ = 0L;

      daaScore_ = 0L;

      blueWork_ = "";

      pruningPoint_ = "";

      blueScore_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protowire.Rpc.internal_static_protowire_RpcBlockHeader_descriptor;
    }

    @java.lang.Override
    public protowire.RpcBlockHeader getDefaultInstanceForType() {
      return protowire.RpcBlockHeader.getDefaultInstance();
    }

    @java.lang.Override
    public protowire.RpcBlockHeader build() {
      protowire.RpcBlockHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protowire.RpcBlockHeader buildPartial() {
      protowire.RpcBlockHeader result = new protowire.RpcBlockHeader(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      if (parentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          parents_ = java.util.Collections.unmodifiableList(parents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.parents_ = parents_;
      } else {
        result.parents_ = parentsBuilder_.build();
      }
      result.hashMerkleRoot_ = hashMerkleRoot_;
      result.acceptedIdMerkleRoot_ = acceptedIdMerkleRoot_;
      result.utxoCommitment_ = utxoCommitment_;
      result.timestamp_ = timestamp_;
      result.bits_ = bits_;
      result.nonce_ = nonce_;
      result.daaScore_ = daaScore_;
      result.blueWork_ = blueWork_;
      result.pruningPoint_ = pruningPoint_;
      result.blueScore_ = blueScore_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protowire.RpcBlockHeader) {
        return mergeFrom((protowire.RpcBlockHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protowire.RpcBlockHeader other) {
      if (other == protowire.RpcBlockHeader.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (parentsBuilder_ == null) {
        if (!other.parents_.isEmpty()) {
          if (parents_.isEmpty()) {
            parents_ = other.parents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureParentsIsMutable();
            parents_.addAll(other.parents_);
          }
          onChanged();
        }
      } else {
        if (!other.parents_.isEmpty()) {
          if (parentsBuilder_.isEmpty()) {
            parentsBuilder_.dispose();
            parentsBuilder_ = null;
            parents_ = other.parents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            parentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParentsFieldBuilder() : null;
          } else {
            parentsBuilder_.addAllMessages(other.parents_);
          }
        }
      }
      if (!other.getHashMerkleRoot().isEmpty()) {
        hashMerkleRoot_ = other.hashMerkleRoot_;
        onChanged();
      }
      if (!other.getAcceptedIdMerkleRoot().isEmpty()) {
        acceptedIdMerkleRoot_ = other.acceptedIdMerkleRoot_;
        onChanged();
      }
      if (!other.getUtxoCommitment().isEmpty()) {
        utxoCommitment_ = other.utxoCommitment_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getBits() != 0) {
        setBits(other.getBits());
      }
      if (other.getNonce() != 0L) {
        setNonce(other.getNonce());
      }
      if (other.getDaaScore() != 0L) {
        setDaaScore(other.getDaaScore());
      }
      if (!other.getBlueWork().isEmpty()) {
        blueWork_ = other.blueWork_;
        onChanged();
      }
      if (!other.getPruningPoint().isEmpty()) {
        pruningPoint_ = other.pruningPoint_;
        onChanged();
      }
      if (other.getBlueScore() != 0L) {
        setBlueScore(other.getBlueScore());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protowire.RpcBlockHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protowire.RpcBlockHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>uint32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<protowire.RpcBlockLevelParents> parents_ =
      java.util.Collections.emptyList();
    private void ensureParentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        parents_ = new java.util.ArrayList<protowire.RpcBlockLevelParents>(parents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protowire.RpcBlockLevelParents, protowire.RpcBlockLevelParents.Builder, protowire.RpcBlockLevelParentsOrBuilder> parentsBuilder_;

    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public java.util.List<protowire.RpcBlockLevelParents> getParentsList() {
      if (parentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parents_);
      } else {
        return parentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public int getParentsCount() {
      if (parentsBuilder_ == null) {
        return parents_.size();
      } else {
        return parentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public protowire.RpcBlockLevelParents getParents(int index) {
      if (parentsBuilder_ == null) {
        return parents_.get(index);
      } else {
        return parentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder setParents(
        int index, protowire.RpcBlockLevelParents value) {
      if (parentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParentsIsMutable();
        parents_.set(index, value);
        onChanged();
      } else {
        parentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder setParents(
        int index, protowire.RpcBlockLevelParents.Builder builderForValue) {
      if (parentsBuilder_ == null) {
        ensureParentsIsMutable();
        parents_.set(index, builderForValue.build());
        onChanged();
      } else {
        parentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder addParents(protowire.RpcBlockLevelParents value) {
      if (parentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
      } else {
        parentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder addParents(
        int index, protowire.RpcBlockLevelParents value) {
      if (parentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParentsIsMutable();
        parents_.add(index, value);
        onChanged();
      } else {
        parentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder addParents(
        protowire.RpcBlockLevelParents.Builder builderForValue) {
      if (parentsBuilder_ == null) {
        ensureParentsIsMutable();
        parents_.add(builderForValue.build());
        onChanged();
      } else {
        parentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder addParents(
        int index, protowire.RpcBlockLevelParents.Builder builderForValue) {
      if (parentsBuilder_ == null) {
        ensureParentsIsMutable();
        parents_.add(index, builderForValue.build());
        onChanged();
      } else {
        parentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder addAllParents(
        java.lang.Iterable<? extends protowire.RpcBlockLevelParents> values) {
      if (parentsBuilder_ == null) {
        ensureParentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parents_);
        onChanged();
      } else {
        parentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder clearParents() {
      if (parentsBuilder_ == null) {
        parents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        parentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public Builder removeParents(int index) {
      if (parentsBuilder_ == null) {
        ensureParentsIsMutable();
        parents_.remove(index);
        onChanged();
      } else {
        parentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public protowire.RpcBlockLevelParents.Builder getParentsBuilder(
        int index) {
      return getParentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public protowire.RpcBlockLevelParentsOrBuilder getParentsOrBuilder(
        int index) {
      if (parentsBuilder_ == null) {
        return parents_.get(index);  } else {
        return parentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public java.util.List<? extends protowire.RpcBlockLevelParentsOrBuilder> 
         getParentsOrBuilderList() {
      if (parentsBuilder_ != null) {
        return parentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parents_);
      }
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public protowire.RpcBlockLevelParents.Builder addParentsBuilder() {
      return getParentsFieldBuilder().addBuilder(
          protowire.RpcBlockLevelParents.getDefaultInstance());
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public protowire.RpcBlockLevelParents.Builder addParentsBuilder(
        int index) {
      return getParentsFieldBuilder().addBuilder(
          index, protowire.RpcBlockLevelParents.getDefaultInstance());
    }
    /**
     * <code>repeated .protowire.RpcBlockLevelParents parents = 12;</code>
     */
    public java.util.List<protowire.RpcBlockLevelParents.Builder> 
         getParentsBuilderList() {
      return getParentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protowire.RpcBlockLevelParents, protowire.RpcBlockLevelParents.Builder, protowire.RpcBlockLevelParentsOrBuilder> 
        getParentsFieldBuilder() {
      if (parentsBuilder_ == null) {
        parentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protowire.RpcBlockLevelParents, protowire.RpcBlockLevelParents.Builder, protowire.RpcBlockLevelParentsOrBuilder>(
                parents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        parents_ = null;
      }
      return parentsBuilder_;
    }

    private java.lang.Object hashMerkleRoot_ = "";
    /**
     * <code>string hashMerkleRoot = 3;</code>
     * @return The hashMerkleRoot.
     */
    public java.lang.String getHashMerkleRoot() {
      java.lang.Object ref = hashMerkleRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashMerkleRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hashMerkleRoot = 3;</code>
     * @return The bytes for hashMerkleRoot.
     */
    public com.google.protobuf.ByteString
        getHashMerkleRootBytes() {
      java.lang.Object ref = hashMerkleRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashMerkleRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hashMerkleRoot = 3;</code>
     * @param value The hashMerkleRoot to set.
     * @return This builder for chaining.
     */
    public Builder setHashMerkleRoot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hashMerkleRoot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hashMerkleRoot = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashMerkleRoot() {
      
      hashMerkleRoot_ = getDefaultInstance().getHashMerkleRoot();
      onChanged();
      return this;
    }
    /**
     * <code>string hashMerkleRoot = 3;</code>
     * @param value The bytes for hashMerkleRoot to set.
     * @return This builder for chaining.
     */
    public Builder setHashMerkleRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hashMerkleRoot_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object acceptedIdMerkleRoot_ = "";
    /**
     * <code>string acceptedIdMerkleRoot = 4;</code>
     * @return The acceptedIdMerkleRoot.
     */
    public java.lang.String getAcceptedIdMerkleRoot() {
      java.lang.Object ref = acceptedIdMerkleRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptedIdMerkleRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string acceptedIdMerkleRoot = 4;</code>
     * @return The bytes for acceptedIdMerkleRoot.
     */
    public com.google.protobuf.ByteString
        getAcceptedIdMerkleRootBytes() {
      java.lang.Object ref = acceptedIdMerkleRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptedIdMerkleRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string acceptedIdMerkleRoot = 4;</code>
     * @param value The acceptedIdMerkleRoot to set.
     * @return This builder for chaining.
     */
    public Builder setAcceptedIdMerkleRoot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      acceptedIdMerkleRoot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string acceptedIdMerkleRoot = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcceptedIdMerkleRoot() {
      
      acceptedIdMerkleRoot_ = getDefaultInstance().getAcceptedIdMerkleRoot();
      onChanged();
      return this;
    }
    /**
     * <code>string acceptedIdMerkleRoot = 4;</code>
     * @param value The bytes for acceptedIdMerkleRoot to set.
     * @return This builder for chaining.
     */
    public Builder setAcceptedIdMerkleRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      acceptedIdMerkleRoot_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utxoCommitment_ = "";
    /**
     * <code>string utxoCommitment = 5;</code>
     * @return The utxoCommitment.
     */
    public java.lang.String getUtxoCommitment() {
      java.lang.Object ref = utxoCommitment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utxoCommitment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string utxoCommitment = 5;</code>
     * @return The bytes for utxoCommitment.
     */
    public com.google.protobuf.ByteString
        getUtxoCommitmentBytes() {
      java.lang.Object ref = utxoCommitment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utxoCommitment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string utxoCommitment = 5;</code>
     * @param value The utxoCommitment to set.
     * @return This builder for chaining.
     */
    public Builder setUtxoCommitment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utxoCommitment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string utxoCommitment = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtxoCommitment() {
      
      utxoCommitment_ = getDefaultInstance().getUtxoCommitment();
      onChanged();
      return this;
    }
    /**
     * <code>string utxoCommitment = 5;</code>
     * @param value The bytes for utxoCommitment to set.
     * @return This builder for chaining.
     */
    public Builder setUtxoCommitmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utxoCommitment_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int bits_ ;
    /**
     * <code>uint32 bits = 7;</code>
     * @return The bits.
     */
    @java.lang.Override
    public int getBits() {
      return bits_;
    }
    /**
     * <code>uint32 bits = 7;</code>
     * @param value The bits to set.
     * @return This builder for chaining.
     */
    public Builder setBits(int value) {
      
      bits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 bits = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBits() {
      
      bits_ = 0;
      onChanged();
      return this;
    }

    private long nonce_ ;
    /**
     * <code>uint64 nonce = 8;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }
    /**
     * <code>uint64 nonce = 8;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(long value) {
      
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 nonce = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      
      nonce_ = 0L;
      onChanged();
      return this;
    }

    private long daaScore_ ;
    /**
     * <code>uint64 daaScore = 9;</code>
     * @return The daaScore.
     */
    @java.lang.Override
    public long getDaaScore() {
      return daaScore_;
    }
    /**
     * <code>uint64 daaScore = 9;</code>
     * @param value The daaScore to set.
     * @return This builder for chaining.
     */
    public Builder setDaaScore(long value) {
      
      daaScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 daaScore = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDaaScore() {
      
      daaScore_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object blueWork_ = "";
    /**
     * <code>string blueWork = 10;</code>
     * @return The blueWork.
     */
    public java.lang.String getBlueWork() {
      java.lang.Object ref = blueWork_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blueWork_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blueWork = 10;</code>
     * @return The bytes for blueWork.
     */
    public com.google.protobuf.ByteString
        getBlueWorkBytes() {
      java.lang.Object ref = blueWork_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blueWork_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blueWork = 10;</code>
     * @param value The blueWork to set.
     * @return This builder for chaining.
     */
    public Builder setBlueWork(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blueWork_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blueWork = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlueWork() {
      
      blueWork_ = getDefaultInstance().getBlueWork();
      onChanged();
      return this;
    }
    /**
     * <code>string blueWork = 10;</code>
     * @param value The bytes for blueWork to set.
     * @return This builder for chaining.
     */
    public Builder setBlueWorkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blueWork_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pruningPoint_ = "";
    /**
     * <code>string pruningPoint = 14;</code>
     * @return The pruningPoint.
     */
    public java.lang.String getPruningPoint() {
      java.lang.Object ref = pruningPoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pruningPoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pruningPoint = 14;</code>
     * @return The bytes for pruningPoint.
     */
    public com.google.protobuf.ByteString
        getPruningPointBytes() {
      java.lang.Object ref = pruningPoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pruningPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pruningPoint = 14;</code>
     * @param value The pruningPoint to set.
     * @return This builder for chaining.
     */
    public Builder setPruningPoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pruningPoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pruningPoint = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPruningPoint() {
      
      pruningPoint_ = getDefaultInstance().getPruningPoint();
      onChanged();
      return this;
    }
    /**
     * <code>string pruningPoint = 14;</code>
     * @param value The bytes for pruningPoint to set.
     * @return This builder for chaining.
     */
    public Builder setPruningPointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pruningPoint_ = value;
      onChanged();
      return this;
    }

    private long blueScore_ ;
    /**
     * <code>uint64 blueScore = 13;</code>
     * @return The blueScore.
     */
    @java.lang.Override
    public long getBlueScore() {
      return blueScore_;
    }
    /**
     * <code>uint64 blueScore = 13;</code>
     * @param value The blueScore to set.
     * @return This builder for chaining.
     */
    public Builder setBlueScore(long value) {
      
      blueScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 blueScore = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlueScore() {
      
      blueScore_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protowire.RpcBlockHeader)
  }

  // @@protoc_insertion_point(class_scope:protowire.RpcBlockHeader)
  private static final protowire.RpcBlockHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protowire.RpcBlockHeader();
  }

  public static protowire.RpcBlockHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcBlockHeader>
      PARSER = new com.google.protobuf.AbstractParser<RpcBlockHeader>() {
    @java.lang.Override
    public RpcBlockHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RpcBlockHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RpcBlockHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcBlockHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protowire.RpcBlockHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

