// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package protowire;

public interface RpcTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protowire.RpcTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .protowire.RpcTransactionInput inputs = 2;</code>
   */
  java.util.List<protowire.RpcTransactionInput> 
      getInputsList();
  /**
   * <code>repeated .protowire.RpcTransactionInput inputs = 2;</code>
   */
  protowire.RpcTransactionInput getInputs(int index);
  /**
   * <code>repeated .protowire.RpcTransactionInput inputs = 2;</code>
   */
  int getInputsCount();
  /**
   * <code>repeated .protowire.RpcTransactionInput inputs = 2;</code>
   */
  java.util.List<? extends protowire.RpcTransactionInputOrBuilder> 
      getInputsOrBuilderList();
  /**
   * <code>repeated .protowire.RpcTransactionInput inputs = 2;</code>
   */
  protowire.RpcTransactionInputOrBuilder getInputsOrBuilder(
      int index);

  /**
   * <code>repeated .protowire.RpcTransactionOutput outputs = 3;</code>
   */
  java.util.List<protowire.RpcTransactionOutput> 
      getOutputsList();
  /**
   * <code>repeated .protowire.RpcTransactionOutput outputs = 3;</code>
   */
  protowire.RpcTransactionOutput getOutputs(int index);
  /**
   * <code>repeated .protowire.RpcTransactionOutput outputs = 3;</code>
   */
  int getOutputsCount();
  /**
   * <code>repeated .protowire.RpcTransactionOutput outputs = 3;</code>
   */
  java.util.List<? extends protowire.RpcTransactionOutputOrBuilder> 
      getOutputsOrBuilderList();
  /**
   * <code>repeated .protowire.RpcTransactionOutput outputs = 3;</code>
   */
  protowire.RpcTransactionOutputOrBuilder getOutputsOrBuilder(
      int index);

  /**
   * <code>uint64 lockTime = 4;</code>
   * @return The lockTime.
   */
  long getLockTime();

  /**
   * <code>string subnetworkId = 5;</code>
   * @return The subnetworkId.
   */
  java.lang.String getSubnetworkId();
  /**
   * <code>string subnetworkId = 5;</code>
   * @return The bytes for subnetworkId.
   */
  com.google.protobuf.ByteString
      getSubnetworkIdBytes();

  /**
   * <code>uint64 gas = 6;</code>
   * @return The gas.
   */
  long getGas();

  /**
   * <code>string payload = 8;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 8;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>.protowire.RpcTransactionVerboseData verboseData = 9;</code>
   * @return Whether the verboseData field is set.
   */
  boolean hasVerboseData();
  /**
   * <code>.protowire.RpcTransactionVerboseData verboseData = 9;</code>
   * @return The verboseData.
   */
  protowire.RpcTransactionVerboseData getVerboseData();
  /**
   * <code>.protowire.RpcTransactionVerboseData verboseData = 9;</code>
   */
  protowire.RpcTransactionVerboseDataOrBuilder getVerboseDataOrBuilder();
}
